### ISSUE TITLE
Add release

### ISSUE THREAD

**Issue by psibre** [ElDeveloper/macfusion2#12]
GitHub has reintroduced downloads as a feature of its [Releases](https://help.github.com/articles/about-releases/) feature. Please consider creating a release, and attaching a binary package to it. This makes workarounds such as [your blog post](http://yoshikee.tumblr.com/post/39202253046/eldeveloper-macfusion) unnecessary.

**Comment by ElDeveloper** [comment]
Will do this over the weekend, seems like a good idea, thanks!

**Comment by ElDeveloper** [comment]
Done, [link](https://github.com/ElDeveloper/macfusion2/releases/tag/2.1-dev).

Thanks for the idea @psibre
