### ISSUE TITLE
Add support for key-based authentication

### ISSUE THREAD

**Issue by duck57** [ElDeveloper/macfusion2#16]
Currently (as of the 2.05 dev version), all authentication is done via passwords.  Adding support for key-based authentication will allow MacFusion to play nicer with servers which use that.

**Comment by ElDeveloper** [comment]
While unofficial, this is actually supported, if you setup you
.ssh/config file and describe the filepath to your key, MacFusion should
be able to use that directly.

**Comment by duck57** [comment]
In case anyone runs into this in the future: make sure that the `Host` you have with your `IdentityFile` in `.ssh/config` is the same as the line you have as the Host in MacFusion.  Don't enter a password in the setup and don't add `IdentityFile .ssh/config` to the Extra  Options, or else it won't work.  It will mount your server nicely with that set-up.

**Comment by ElDeveloper** [comment]
Thanks for the information @duck57.
