### ISSUE TITLE
Not compatible with OS X Sierra

### ISSUE THREAD

**Issue by ethanx94** [ElDeveloper/macfusion2#17]
Crossposted from mgorbach/macfusion2

Macfusion will not run on OS X Sierra stating it is incompatible with this version of OS X.

The exact error I'm getting when trying to run the program directly:

> dyld: Library not loaded: @rpath/MFCore.framework/Versions/A/MFCore
  Referenced from: /Applications/Macfusion.app/Contents/MacOS/Macfusion
  Reason: no suitable image found.  Did find:
	/Applications/Macfusion.app/Contents/MacOS/../Frameworks/MFCore.framework/Versions/A/MFCore: cannot load '/Applications/Macfusion.app/Contents/MacOS/../Frameworks/MFCore.framework/Versions/A/MFCore' because Objective-C garbage collection is not supported
Abort trap: 6

**Comment by alexwhittemore** [comment]
If I recall, garbage collection has been completely deprecated in the latest framework version. I fear this might require a prohibitive overhaul to achieve compatibility... :(

**Comment by ElDeveloper** [comment]
@alexwhittemore is right. I remember trying to get started with the conversion to ARC, but some of the dependencies, IconFamily and Sparkle (I think), required changes to their API, etc.

If anyone has enough interest in this, we could probably coordinate something and make this happen. Regrettably, I don't use Macfusion all that much myself anymore, so this conversion is not at the top of my list of priorities. However, I would be willing to take over this with some help.

**Comment by tessus** [comment]
I mentioned this issue like 2 years ago - see #11 

Sparkle isn't a problem, because they have 2 versions. one with ARC, the other without. so you only have to replace it and done.

The problem are the other dependencies...

**Comment by ElDeveloper** [comment]
Time surely flies ⏳!

Let's continue the conversation over at #11.
