### ISSUE TITLE
Mount process has terminated unexpectedly

### ISSUE THREAD

**Issue by mickey9801** [ElDeveloper/macfusion2#24]
Reference to #11 : I have tried 2.1.1-dev on MacBook Pro '13 late, Sierra. The app launched normally but when I try to mount a remote drive, it turned out an error message "Could not mount filesystem: Mount process has terminated unexpectedly"

I have added the key file to ssh-agent and set Mount Point to non-exists folder "/Users//Volumes", and tried to assign a Volume Name or leave it blank (Default), both got failed.

I have tried to `mkdir $HOME/Volumes` and use ~\Volumes as mount point. The problem still exists and the directory I have created is being deleted. I have also chown the Volumes directory to root.staff but still not work.

**Comment by zmonteca** [comment]
sudo chmod o+w /Volumes

**Comment by mickey9801** [comment]
I have tried this but got an error:
1. $ sudo chmod o+w /Volumes
2. Set mount point to /Volumes and mount it
Error: Could not mount filesystem: Mount path directory in use.

**Comment by ElDeveloper** [comment]
@mickey9801, have you tried testing the chances in #20?

**Comment by mickey9801** [comment]
Yes.

I have downloaded release 2 and test it with:

1. sudo chmod o+w /Volumes; set mount point to /Volumes/;
Error: Could not mount filesystem: Mount path directory in use.

2. mkdir /Users/myname/Volumes;sudo chmod 777 /Users/myname/Volumes/;set mount point to /Users/myname/Volumes/
Error: Could not mount filesystem: Mount process has terminated unexpectedly, then the directory being removed;

**Comment by ElDeveloper** [comment]
Can you try to mount the desired filesystem using the command line?

```bash
mkdir the-mountpoint

/Applications/Macfusion.app/Contents/PlugIns/sshfs.mfplugin/Contents/Resources/sshfs-static yourusername@servername: the-mountpoint
```

If you get an error, can you please post that here?

**Comment by mickey9801** [comment]
Tried and failed.

> [me@macbook ~]# mkdir Volumes
[me@macbook ~]# /Applications/Macfusion.app/Contents/PlugIns/sshfs.mfplugin/Contents/Resources/sshfs-static myusername@my.server: Volumes
dyld: Library not loaded: /usr/local/lib/libfuse.0.dylib
  Referenced from: /Applications/Macfusion.app/Contents/PlugIns/sshfs.mfplugin/Contents/Resources/sshfs-static
  Reason: image not found
Abort trap: 6

**Comment by tessus** [comment]
@mickey9801 The [README.md](https://github.com/ElDeveloper/macfusion2/blob/master/README.md) states:

For Mac OS X 10.7 and greater, you need Fuse for OSX, note that you will need to check the "_install MacFUSE compatibility layer_" option during the installation process, otherwise some parts of the software will be broken.

--

This will change in the future, but for now you will have to install the compat layer.

**Comment by mickey9801** [comment]
I have installed FUSE for macOS and upgraded to 3.5.2 before I try this build. I removed the FUSE for macOS and reinstalled both FUSE for macOS 3.5.2 and SSHFS 2.5.0 again, and now it works.

Thank you

**Comment by ElDeveloper** [comment]
🎉 !!

**Comment by wcgall** [comment]
Also tried & failed:

> /Applications/Macfusion.app/Contents/PlugIns/sshfs.mfplugin/Contents/Resources/sshfs-static myusername@my.server: Volumes
> sshfs: cannot find sshnodelay.so
> warning: ssh nodelay workaround disabled
> myusername@my.server's password: 
> the OSXFUSE file system is not available (255)
>

**Comment by tessus** [comment]
@wcgall please do a
`otool -L /Applications/Macfusion.app/Contents/PlugIns/sshfs.mfplugin/Contents/Resources/sshfs-static`

what is the output? Do you see a `/usr/local/lib/libfuse.0.dylib`? if yes, does this file exist?

**Comment by wcgall** [comment]
> /Applications/Macfusion.app/Contents/PlugIns/sshfs.mfplugin/Contents/Resources/sshfs-static (architecture i386):
> 	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 136.0.0)
> 	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 677.15.0)
> 	/usr/local/lib/libfuse.0.dylib (compatibility version 1.0.0, current version 1.0.0)
> 	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
> 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.0.0)
> 	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 32.0.0)
> 	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 476.10.0)
> /Applications/Macfusion.app/Contents/PlugIns/sshfs.mfplugin/Contents/Resources/sshfs-static (architecture ppc7400):
> 	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 136.0.0)
> 	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 677.15.0)
> 	/usr/local/lib/libfuse.0.dylib (compatibility version 1.0.0, current version 1.0.0)
> 	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
> 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.0.0)
> 	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 32.0.0)
> 	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 476.10.0)

**Comment by tessus** [comment]
@wcgall thanks, what is the output of `ls /usr/local/lib/libfuse.0.dylib`

**Comment by wcgall** [comment]
> /usr/local/lib/libfuse.0.dylib

(Yes, it's there.  Sorry, I thought that was indicated by the previous.)

**Comment by tessus** [comment]
No, the otool output only shows against which libs the binary is linked. This does not mean the file really exists in the file system.

Is the file `libfuse.0.dylib` really in the directory `/usr/local/lib`

Your error message suggests that something is not installed correctly.

**Comment by wcgall** [comment]
![screen shot 2016-10-24 at oct 24 2016 - 3 21 18 pm](https://cloud.githubusercontent.com/assets/22895448/19660413/a61d2132-99fd-11e6-9ba6-dc305b574f33.png)

**Comment by tessus** [comment]
@ElDeveloper any ideas? this makes no sense.

**Comment by ElDeveloper** [comment]
@wcgall, maybe try reinstalling macOS Fuse?

**Comment by wcgall** [comment]
Tried that.

**Comment by cometsong** [comment]
I'm getting same error message on attempted mounting.
Started by using a "Favorite" that had stayed from the older version.

When that failed, came to this issue page, chgrp'd and chmod'd the /Volumes directory, changed mount point to a user-owned directory.
Did a complete uninstall/reinstall of MacFusion, OSXFuse, SSHFS to their latest versions (using the "2.1.1-dev.3" ver of Macfusion).

Still no luck.
I *can* successfully mount the remote server on that same directory using the `sshfs` program from osxfuse repository.
Macfusion, however, still gives the "Could not mount filesystem: Mount process has terminated unexpectedly." error.  :(
