### ISSUE TITLE
Compiled Version

### ISSUE THREAD

**Issue by janstieler** [ElDeveloper/macfusion2#31]
Hi,
is it possible to release a compiled version of your fork?

Cheers

**Comment by ikozhukhov** [comment]
+1
need working version on sierra

**Comment by tessus** [comment]
Have you tried the latest [Sierra Pre-release 3](https://github.com/ElDeveloper/macfusion2/releases/tag/2.1.1-dev.3)? It has a compiled version attached ([Macfusion.zip](https://github.com/ElDeveloper/macfusion2/releases/download/2.1.1-dev.3/Macfusion.zip)).

**Comment by ikozhukhov** [comment]
thanks a lot, it is working fine!
